# Data
path: C:/Users/tinao/OneDrive/Desktop/Keypoint/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [13, 2]  # [number of keypoints, number of dim]
flip_idx: [9, 10, 7, 8, 6, 5, 4, 2, 3, 0, 1, 11, 12]

# Classes
names:
  0: Black_Rhino_Left
  1: White_Rhino_Left
  2: Black_Rhino_Right
  3: White_Rhino_Right 
